<a href="https://colab.research.google.com/github/dcm5455/python-basics/blob/main/python_basics2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

how to install numpy

In [ ]:
pip install numpy


In [ ]:
import numpy as np

create 1-d array

In [ ]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


create 2-d or multidimensional array

In [ ]:
a=np.array([[1,2,3],[10,20,30]])

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
np.indices((4,4))

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(a.dtype)

int64


In [ ]:
import numpy as np

l=range(100)
import sys
a=1
print(sys.getsizeof(a))

28


numpy vs list speed

In [ ]:
import time
import sys

In [ ]:
size=1000000
l1=range(size)
l2=range(size)

n1=np.arange(size)
n2=np.arange(size)

#list
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

#numpy arrays
start=time.time()
result=n1+n2
print((time.time()-start)*1000)


116.43409729003906
14.105796813964844


reshape

numpy operations

In [ ]:
a=np.array([[1,2,3],[10,20,30]])
print(a.ndim)

2


reshape


In [ ]:
a=np.array([[1,2,3],
           [10,20,30]])


array mathematical operations

In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)
print(x+y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [ ]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a=a.reshape(3,2)
print(a)
np.reshape(a,(2,3))

[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print(a)
print(a.size)
np.reshape(a,6)

[[0 1]
 [2 3]
 [4 5]]
6


array([0, 1, 2, 3, 4, 5])

In [ ]:
import pandas as pd
import numpy as np
a=np.array(['g','o','e','d','u'])
p=pd.Series(a)
print(p)

0    g
1    o
2    e
3    d
4    u
dtype: object


In [ ]:
s1=pd.Series(np.random.(5),index=['a','b','c','d','e'])

SyntaxError: ignored

In [ ]:
data ={'pi':3.14,'e':2.71}
print(data)
s3=pd.Series(data)
print(s3)

{'pi': 3.14, 'e': 2.71}
pi    3.14
e     2.71
dtype: float64


In [ ]:
s1

NameError: ignored

In [ ]:
print(a.flatten())

[0 1 2 3 4 5]


# ***pandas***

In [ ]:
pip install pandas